name: Deploy to S3

on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Set environment based on branch
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ASTRO_SITE=https://beeyouself.com/" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=${{ secrets.S3_PROD_BUCKET_NAME }}" >> $GITHUB_ENV
          else
            echo "ASTRO_SITE=https://yourdevelopmentdomain.com" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=${{ secrets.S3_DEV_BUCKET_NAME }}" >> $GITHUB_ENV
          fi

      - name: Build Astro project
        run: npm run build

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://$S3_BUCKET_NAME --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
